### PR TITLE
V1.1

### PR DESCRIPTION
**Pull request by bituka**

### CODE REVIEW

**Comment by lightshire** [comment]
please add gitignore to bower_components then delete them from the repo.

It'll cause alot of merge confllicts in the future when vendor files get updated.

**Comment by lightshire** [comment]
why not make the static page `apicentric` + `static'?

**Comment by bituka** [comment]
will do on the bower components. 

good apicentric will be probably on next version. I wanted it to be very basic on the v1.

**Comment by lightshire** [comment]
If your primary agenda is to be very basic.

I suggest not using Laravel in entirety. Should use either
- vanilla js
- reactjs
- angularjs2 (as suggested by @jpalala)

## 

Going to add this to the agenda for tomorrow.

**Comment by bituka** [comment]
What I mean here is basic Laravel, as this is the name of the group and I am just trying to learn it. 

Anyways, no prob. Let me know what's going to be the result of your agenda, so maybe you can start it and I'll follow.

**Comment by rmrhz** [comment]
Excuse me? You're saying that you made the Laravel PH as a guinea pig to learn?

**Comment by bituka** [comment]
@rmrhz your question is too broad to answer. can you elaborate?

**Comment by rmrhz** [comment]
How does "making the project a guinea pig" **too broad**?

**Comment by nicopenaredondo** [comment]
@rmrhz ( ͡° ͜ʖ ͡°)

**Comment by srph** [comment]
If you wanted to make it a learning experience, I suggest you don't self-merge and ask someone to review (especially in groups such as this).

**Comment by lightshire** [comment]
grabs popcorn.

**Comment by srph** [comment]
this doesn't have to be controversial or anything.

anyway, lph doesn't have any roadmap as far as i'm concerned, so people in general have no idea what to help out.

@lightshire i don't get why we need this to be api-centric. static pages seems to be the goal; html alone will do. it doesn't even have to be built with laravel unless there's a specific goal.

lastly, i'm wondering why the repo is named `LaravelPHStaticPage` instead of `laravel-philippines.github.io` or `laravel-ph.org`.

cc @jpalala

**Comment by lightshire** [comment]
@srph check comment from the other issue.

I agree HTML alone would do. 

## 

This is a big issue. This should not be debated yet. Unless the set of proper features are on board.

## 

Re: roadmap - this has to be ironed out first. And i suggest starting from scratch. including deleting all repositories that are non-compliant with the plan.

## 

hindi ibg sbhn Laravel Philippines eh lahat ng ggwin eh gawa sa laravel.

**Comment by bituka** [comment]
@srph 

it was a mistake. Please review commit history.

**Comment by bituka** [comment]
@lightshire 

up to you pare... i was just playing around laravel anyways... was just doing something lang para may madisplay sa page... 

no one is doing a thing anyways, all i can see are suggestions. ika nga e puro mando.

**Comment by nicopenaredondo** [comment]
Question: whats the difference between this repo and the one that NuWorks are currently developing? Based on the fb post that ive saw in the group

**Pull request closed without merging**
